version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: carsInventory_container
    image: mongo:latest
    ports:
      - 27018:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    image: nodeapp
    ports:
      - 3050:3050
    depends_on: 
      - mongo_db

  test:
    image: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "test"]
    depends_on: 
      - mongo_db
    environment:
      IS_TEST: true

volumes:
  mongo_data: {}